### ISSUE TITLE
FYI: Homepage still references 5.30.2, not 5.30.3

### ISSUE THREAD

**Issue by sisyphus** [StrawberryPerl/Perl-Dist-Strawberry#17]
Hi,
The title says it all.
I assume that the homepage (http://strawberryperl.com) is supposed to specify the latest release - in which case it requires updating.

Cheers,
Rob

**Comment by zdm** [comment]
And no perl 5.32.0 provided.

**Comment by sisyphus** [comment]
I don't read too much into the the non-appearance of Strawberry-5.32.0. 
At least, not yet, anyway ... though perl-5.32.0 was released almost 7 weeks ago.
(I assume it's just that kmx is busy.)

Cheers,
Rob

**Comment by shogo82148** [comment]
@kmx has already built Strawberry-5.32.0 (ref. https://github.com/StrawberryPerl/strawberryperl.com/issues/23#issuecomment-671022737 ).
And the release note of Strawberry-5.32.0 was once committed (https://github.com/StrawberryPerl/strawberryperl.com/commit/10c23bda7ae669203a2d80f2bd79a7b89eff0ac4),
but it was reverted (https://github.com/StrawberryPerl/strawberryperl.com/commit/0d7f62f46ec2d74ec444496a29cd9718771768c0)

So I'm guessing @kmx is facing another problem, but I don't know the actual reason.

**Comment by sisyphus** [comment]
Interesting.
I can see:
http://strawberryperl.com/download/5.32.0.1/strawberry-perl-5.32.0.1-64bit.msi
http://strawberryperl.com/download/5.32.0.1/strawberry-perl-5.32.0.1-32bit.msi

and I've just downloaded and installed:
http://strawberryperl.com/download/5.32.0.1/strawberry-perl-5.32.0.1-64bit-portable.zip

But it's a little concerning that the website hasn't been updated to reflect the availability of these files.
I do hope that @kmx is ok.

Maybe there's some problem with these builds ... or maybe some problem with the obstruction known as @adamkennedy.
Just have to wait and see, I guess.

I did note that these 5.32.0 builds don't provide an updated version of gcc. (It's still gcc-8.3.0, as with 5.30.x.)
Since the mingw-w64 project has stopped releasing built compilers, I've been looking forward to obtaining an annual update via Strawberry Perl ... but not this year, it seems.

Cheers,
Rob

**Comment by kmx** [comment]
fixed

**Comment by sisyphus** [comment]
When I visit http://strawberryperl.com/ I still see "Recommended version" links to:
http://strawberryperl.com/download/5.32.0.1/strawberry-perl-5.32.0.1-64bit.msi
and
http://strawberryperl.com/download/5.32.0.1/strawberry-perl-5.32.0.1-32bit.msi

Assuming this is not some unshakable caching issue at my end, could you explain your reasoning for recommending those specific versions ?

**Comment by sisyphus** [comment]
Apologies - my brainfart.
Can't tell the difference between perl-5.30.2 and perl-5.32.0
