### ISSUE TITLE
Can't load Win32.xs.dll when running cpanm

### ISSUE THREAD

**Issue by realflash** [StrawberryPerl/Perl-Dist-Strawberry#195]
I have placed the portable edition into a Windows nanoserver container. A hello world perl script runs OK. I have added the directories in the README so that I can call the perl executable directly, which also works OK. When I run cpanm I get:

`Can't load 'c:/perl/perl/lib/auto/Win32/Win32.xs.dll' for module Win32: load_file:The specified module could not be found at c:/perl/perl/lib/DynaLoader.pm`

PATH is set to 

`c:\Windows\System32;c:\Windows;c:\perl\perl\bin;c:\perl\perl\site\bin;c:\perl\c\bin`

Version is strawberry-perl-5.38.2.2-64bit-portable

If I try to use the cpan module directly I get a different error which I imagine has the same cause:

```
c:\perl>perl -MCPAN -e 'install Dancer;'
Attempt to reload Win32.pm aborted.
Compilation failed in require at c:/perl/perl/lib/Cwd.pm line 592.
```

Could someone please help?

**Comment by sisyphus** [comment]
When I run Strawberry Perl, the following extra directories are included in my PATH:
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Windows\System32\OpenSSH\;
C:\Users\Owner\AppData\Local\Microsoft\WindowsApps

Maybe try adding them (or equivalent) to your path and see if that locates the missing dll.

The usual way of opening up a shell with the correct path automatically set for you is to just double-click on <code>portableshell.bat</code> which you'll find in your <code>C:\Perl</code> directory.

**Comment by tonycoz** [comment]
Do other core dynamic modules load,eg:
```
perl -MDevel::Peek -e0
```

Does Win32 load outside of cpanm:
```
perl -MWin32 -e0
```

**Comment by realflash** [comment]
No error when loading Devel::Peek. Same error when loading Win32 directly.

**Comment by realflash** [comment]
I should add that the same error occurs when trying to load Win32 from the portableshell.

**Comment by mohawk2** [comment]
What do `perl -MV=Win32` and `perl -MV=Devel::Peek` show? (You'll probably have to install `V` first)

**Comment by realflash** [comment]
```
c:\perl>perl -MV=Win32
Win32
        C:\perl\perl\lib\Win32.pm: 0.59

c:\perl>perl -MV=Devel::Peek
Devel::Peek
        C:\perl\perl\lib\Devel\Peek.pm: 1.33
```

**Comment by mohawk2** [comment]
Thank you. Sorry for the multiple questions! If I knew enough to have an immediate solution, I'd go straight to that. Does the `@INC` part of `perl -V` look like this?

```
  @INC:
    C:/perl/perl/site/lib/MSWin32-x64-multi-thread
    C:/perl/perl/site/lib
    C:/perl/perl/vendor/lib
    C:/perl/perl/lib
```

I have `C:\perl\perl\lib\auto\Win32\Win32.xs.dll`, do you? Also, I'm using 5.32.1.1, do you get the same problem with other versions of Strawberry? Have you tried the very latest?

**Comment by sisyphus** [comment]
> I should add that the same error occurs when trying to load Win32 from the portableshell.

This makes me wonder if you've had a bad download, or a bad unpacking of the Strawberry Perl zip.
Does the SHA256 digest of your downloaded strawberry-perl-5.38.2.2-64bit-portable.zip match that shown at https://strawberryperl.com/releases.html (<code>ea451686065d6338d7e4d4a04c9af49f17951d15aa4c2e19ab8cb56fa2373440</code>) ?

What tool did you use to unpack it ? (I use 7z .)
Going back quite a few years, it was not uncommon for some unzip tools to botch the unpacking - depending upon how they were configured. (Winzip was one such tool - but I don't know if that tool even exists any more.)
If the unpacking of the zip package issued warnings/errors, then your Strawberry Perl installation is probably broken.

**Comment by realflash** [comment]
```
c:\perl>perl -e "print \"@INC\""
c:/perl/perl/site/lib
c:/perl/perl/vendor/lib
c:/perl/perl/lib
```
I can confirm that that DLL exists. I'll try a different version.

**Comment by realflash** [comment]
strawberry-perl-5.32.1.1-64bit-portable works OK (has 64-bit and 32-bit editions)
strawberry-perl-5.36.3.1-64bit-portable fails as in my first post (only has 64-bit edition)
strawberry-perl-5.38.2.2-64bit-portable fails as in my first post (only has 64-bit edition)

Some maybe something happened in the change to 64-bit only that broke it?

**Comment by xiaoyafeng** [comment]
Just a guess since I don't have Win11, is there some dll files which win11 doesn't have but old wins has? try install [vc_redist](https://aka.ms/vs/17/release/vc_redist.x64.exe) to see if it help.

**Comment by wchristian** [comment]
you could also try using https://learn.microsoft.com/en-us/sysinternals/downloads/procmon to watch what the perl process is trying to access

**Comment by shawnlaffan** [comment]
The error in the original report usually means a dependent DLL cannot be found.  The can be identified using `objdump`, for which a recursive process is used in [App::PP::Autolink](https://metacpan.org/pod/App::PP::Autolink).  

Running that on my system for the script below produces this as part of its output:
```
pp_autolink -x issue_195.pl
...
Detected link list: c:/perls/5.38.2.2_pdl/c/bin/zlib1__.dll c:/perls/5.38.2.2_pdl/c/bin/libcrypto-1_1-x64__.dll c:/perls/5.38.2.2_pdl/c/bin/libssl-1_1-x64__.dll
...
```

It also warns (via `Module::ScanDeps`) `# Use of runtime loader module Module::Runtime detected.  Results of static scanning may be incomplete.` so there might be other DLLs conditionally loaded that have not been identified.  

So the question is then whether the DLL files have been correctly copied to the nano system.  If they have then something else is going awry.  

I would also recommend trying with SP 5.40, as noted in https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/195#issuecomment-2194248294. 



Script:
```perl
use 5.010;
use warnings;
use Win32;
1;
```

**Comment by shawnlaffan** [comment]
There has been no further discussion in this ticket since 17-Jan.  Hopefully it is resolved, but either way I will close it in a few days if there are no further comments.

**Comment by realflash** [comment]
Definitely not resolved. Perhaps I have missed some ask of me but I was waiting for action from someone else. Has someone else tested it on Windows 11?

**Comment by shawnlaffan** [comment]
> Definitely not resolved. Perhaps I have missed some ask of me but I was waiting for action from someone else. Has someone else tested it on Windows 11?

Thanks for the update.  

Have you tried the steps in https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/195#issuecomment-2597449678?

**Comment by tonycoz** [comment]
I don't see any documentation on what Windows API DLLs nanoserver supports, Win32.xs.dll is linked to the following Win32 system DLLs:
```
ADVAPI32.dll
KERNEL32.dll
msvcrt.dll
NETAPI32.dll
ole32.dll
SHELL32.dll
USER32.dll
USERENV.dll
VERSION.dll
WINHTTP.dll
```
You might want to check all of these are available in `c:\windows\system32`.

Possible suspects that *might* be missing in a minimal image would be shell32.dll, user32.dll, ole32.dll, but they're all pretty basic Windows system DLLs.

**Comment by shawnlaffan** [comment]
One possibility is that the IT people have used the MSI version of Strawberry Perl to first install to `C:\Strprl40.501\` and then moved it (or locally installed it) to `C:/ProgramData/AppV/69BAE760-7169-4C2A-B9C9-F1E18DDC5EAC/F2241D52-0D98-449E-B93D-6ABC6A7CB779/Root/`.  This won't update the registry settings for the local machine.  

Are you able to try with a Strawberry Perl portable edition?  

Also, as @tonycoz noted, this is unrelated to the original topic of this issue.  It would be helpful if you could open a new one.  We can cross-reference back to this where needed.

**Comment by shawnlaffan** [comment]
@realflash - have you been able to try the debugging steps in previous comments?  

https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/195#issuecomment-2597449678
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/195#issuecomment-2823292425
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/195#issuecomment-2849061819

**Comment by realflash** [comment]
Since I first raised this issue the Windows container set up I was using has stopped working and I can't get it running again, so I'm not able to try these additional steps.
